# Playbook to deploy a new server using satellite via the REST API
# 
# All the variables required by the role should be described in
# a newserver vars file. This should be able to handle dictionaries of 
# vars for the role... i.e. multiple builds at once
# this is because the build process is async with Satellite
#
# Alternately this is called from Tower with vars

- name: Delete the servers specified 
  gather_facts: True 
  remote_user: root
  hosts: sat6.parmstrong.ca

  roles:
    - deleteserversbycomment
