---
# This role is used to delete a server from Satellite. If the server is a VM, the VM and all its disks will be deleted as well
# USE WITH CAUTION
#

- set_fact: 
    cmdstring: "hammer --output json host list --search 'comment=""{{ build_comment }}""'"

- name: Get the list of servers with the comment specified
  command: "{{ cmdstring }}"
  register: cmdoutput

- debug:
    msg: "{{ cmdoutput.stdout }}"

- set_fact: servers_to_delete={{ cmdoutput.stdout | from_json | json_query(query) }}
  vars:
    query: "[*].Name"

- debug:
    msg: "The systems to be deleted are: {{ servers_to_delete }}" 

- name: Delete the test VMs
  command: "hammer host delete --name {{ item }}"
  loop: "{{ servers_to_delete }}"

